version: "3"
services:
  web:
    image: microblog
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
    ports:
      - 5000:5000
    environment:
      MYSQL_ROOT_PASSWORD: password
      SECRET_KEY: my-secret-key
      MAIL_PORT: 1025
      DATABASE_URL : mysql+pymysql://microblog:password@db/microblog
    networks:
      - webnet